kind: pipeline
name: rabbot

platform:
  os: linux
  arch: amd64

steps:
  - name: build-rabbot
    image: python:3.7.4-stretch
    environment:
      USERNAME:
        from_secret: pypi_user
      PASSWORD:
        from_secret: pypi_pass
    commands:
      - pip install poetry
      - poetry build
      - poetry publish -u $USERNAME -p $PASSWORD
    when:
      event:
        - push
        - pull_request
